### ISSUE TITLE
[BUG] - Notification System Dialog gets Triggered on AppStart

### ISSUE THREAD

**Issue by delvinwidjaja** [jevonmao/PermissionsSwiftUI#100]
**Describe the bug**
I'm not sure if this is a bug. So basically I have a SwiftUI app, that needs Bluetooth and Notification permissions. The one with Bluetooth works as expected, but for the Notification, the system dialog will appear, even after I remove the method `registerForRemoteNotification()`, which gets called in AppDelegate. How do I handle this?

**Expected behavior**
System dialog shouldn't appear on app start, it should be after clicking on the "Allow"-Button.

**Smartphone (please complete the following information):**
 - Device: iPads and iPhones
 - OS: 14.5+

**Comment by jevonmao** [comment]
all good, i saw this before but j didn't have the chance to reproduce it on my side yet. glad to hear you enjoying the library!
