### ISSUE TITLE
Translation for Allow-Button

### ISSUE THREAD

**Issue by delvinwidjaja** [jevonmao/PermissionsSwiftUI#106]
**Is your feature request related to a problem? Please describe.**
I know the word `Allow` is pretty self-explanatory in all languages. But, is there any possibility to change/translate this? I don't see any method for that. Thanks for the help!

**Comment by jevonmao** [comment]
@delvinwidjaja Yes it's possible to localize, as shown in https://developer.apple.com/documentation/swift_packages/localizing_package_resources. I just need to find some time to implement it. Good feature request.

**Comment by jevonmao** [comment]
@delvinwidjaja Is there any specific language you want to translate to?

**Comment by jevonmao** [comment]
Work in progress on PR #108

**Comment by delvinwidjaja** [comment]
@jevonmao the app I'm working on is available in German, English, Finnish, Italian, and Danish. Thanks!

**Comment by delvinwidjaja** [comment]
Will do that. Thanks again!

**Comment by delvinwidjaja** [comment]
Could you please merge the PR? The PR was closed due to inactivity

**Comment by jevonmao** [comment]
Merged in, let me know if it works.

**Comment by delvinwidjaja** [comment]
@jevonmao could we expect this to be in the new release of the main branch? 
And the translated button for the text that I mentioned here https://github.com/jevonmao/PermissionsSwiftUI/commit/b19c90ca935ca15cc3b8d5ecc2800c320d3d6a0d#r71088108
Thanks!

**Comment by jevonmao** [comment]
@delvinwidjaja Done.
