### ISSUE TITLE
[BUG] - Review rejected due to "PermissionsSwiftUI".

### ISSUE THREAD

**Issue by SNQ-2001** [jevonmao/PermissionsSwiftUI#112]
**Describe the bug**
Adding "PermissionsSwiftUI" to the project will cause the review to be rejected.

See Screenshots for details.

**To Reproduce**
1. Add "PermissionsSwiftUI" to the project
2. Submit your project to App Store Connect

**Screenshots**
Reject details
<img width="1013" alt="スクリーンショット 2022-04-18 13 26 30" src="https://user-images.githubusercontent.com/84154073/163754352-6d1ecd1e-dcd7-4dfd-85af-3de1824b5b45.png">

<img width="1013" alt="スクリーンショット 2022-04-18 13 27 33" src="https://user-images.githubusercontent.com/84154073/163754449-f0fc23e1-bded-43a8-a4d3-004712c436bc.png">

My App
![Screenshot-0417-091821](https://user-images.githubusercontent.com/84154073/163754572-08c37592-e9f9-48d2-80bb-7748e8edf381.png)

**Smartphone (please complete the following information):**
 - OS: iOS14.0 〜 iOS15.4.1

**Comment by jevonmao** [comment]
@SNQ-2001 Interesting, you must be the few people who got rejected. To be honest I don't see much difference between "ALLOW" and "NEXT". But I guess we will have to change the button text for the tracking permission.

**Comment by jevonmao** [comment]
Feel free to open a PR on this one everyone.

**Comment by edorphy** [comment]
Some of the words that I can relate to Apple not liking, as a user I'd decline right away. Words like "Need Permissions" and "If you do not allow it, some functions may not be available" don't build trust or explain to the user what so ever. Out of curiosity, what have you specified in your App Privacy Label? Apple is going to be very sensitive to App Tracking Transparency, and this experience is all but transparent to the user. Food for thought.

If you watch any of the developer videos Apple has, they highly recommend that you ask for permission the last moment before requiring it, and explain WHY.

The screenshot does not illustrate when the screen is being shown; is just shown to the user without any context? I would recommend you build an experience around permissions, and do some explaining. For example, describe what functions won't be available to the user if they don't grant permissions.

**Comment by jevonmao** [comment]
@SNQ-2001 Fixed in v1.5.6. Set the `useAltButton` parameter to true, so it shows "NEXT".
