### ISSUE TITLE
Hide dismissal button when restrictDismissal is set to true

### ISSUE THREAD

**Issue by khuffie** [jevonmao/PermissionsSwiftUI#117]
App Review is starting to reject my updates for two reasons:

- In the permission prompt screen, I allowed users to dismiss it. Apparently this is a no-no. It was solved by setting restrictDismissal to true.
- Now that user's cannot dismiss the screen, this is the rejection notice:
"Specifically, the cancel (“x”) button on the permission screen was still present but unresponsive."

So essentially, Apple wants us to hide the dismissal button completely. This is blocking me from submitting an app update

**Comment by xpnewmedia** [comment]
@khuffie did you get your app submitted with this library?

**Comment by khuffie** [comment]
@xpnewmedia - I created a branch with the source code and did a fix to hide the button, which allowed it to go through the approval process.

**Comment by jevonmao** [comment]
Fixed by PR 5395d233b21d190950ed254700961bcd9298f5f0
