### ISSUE TITLE
[Feature] - UI accessibility

### ISSUE THREAD

**Issue by ryaaanb** [jevonmao/PermissionsSwiftUI#122]
I've recently had a negative review for my app stating that the user couldn't read the additional information for the permissions modal... now looking at it I can see why they found it quite difficult to read as the light grey text merges with the background too much.

![IMG_5336](https://user-images.githubusercontent.com/64364246/203308963-db6747e7-5450-4da8-b829-5c1262842b2f.jpg)

I can't see an option to change either text colours for description or the background colour.

Would be great if these were given as an option!

**Comment by jevonmao** [comment]
Good feature request. 
Just need to expose the color modifier to API.
https://github.com/jevonmao/PermissionsSwiftUI/blob/main/Sources/CorePermissionsSwiftUI/SwiftUI/Shared/PermissionSectionCell.swift#L76
