### ISSUE TITLE
[BUG] - Modal only gets triggered once on app install

### ISSUE THREAD

**Issue by delvinwidjaja** [jevonmao/PermissionsSwiftUI#123]
**Describe the bug**
Modal only gets triggered once when the app is installed

**To Reproduce**
After the user gives permission to the app, the user can revoke the permission manually in settings.
Apparently, the new state of the permissions given can't be detected. When I try to show the modal by observing the permission value it shows nothing.

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 15.5

**Additional context**
I'm not really sure if this is a bug or if this is just not implemented (yet).

**Comment by delvinwidjaja** [comment]
@jevonmao is this the expected behavior?

**Comment by jevonmao** [comment]
@delvinwidjaja Yes this is expected and not a bug. It should check with system API every time, and show the pop up if permission status is `undetermined`. However, if user manually revokes the permission in settings, the status changes to explicitly `denied`, which can only be regranted by user toggling it back in settings. The app cannot show the prompt again. 

But this is a good feature for future, I will open a feature ticket.

**Comment by delvinwidjaja** [comment]
Thanks for the clarification. Cheers!
