### ISSUE TITLE
如果使用Environment来配置本地化会更好。

### ISSUE THREAD

**Issue by xtzPioneer** [jevonmao/PermissionsSwiftUI#133]
目前的自定义描述很是麻烦。

**Comment by jevonmao** [comment]
What do you mean by using environment for localizations?

**Comment by jevonmao** [comment]
Can you maybe link to the relevant documentation please? I will take a look then.

**Comment by xtzPioneer** [comment]
如：
`DatePicker(
                "Time",
                selection: $date,
                displayedComponents: [.date, .hourAndMinute]
)
.environment(\.locale, .init(identifier: "zh-Hans"))
`
