### ISSUE TITLE
[BUG] -  Xcode 14.3.1

### ISSUE THREAD

**Issue by Dave181295** [jevonmao/PermissionsSwiftUI#134]
We just updated Xcode to the latest version and got:

`Compiled module was created by a different version of the compiler; rebuild 'PermissionsSwiftUIMicrophone' and try again: `

**Comment by jevonmao** [comment]
@Dave181295 Let me know if the the error is still occurring. I cannot reproduce in Xcode 14, targeting iOS 14.6 using library version 1.5.7.
