### ISSUE TITLE
iOS 17 Support

### ISSUE THREAD

**Issue by khuffie** [jevonmao/PermissionsSwiftUI#135]
It seems Apple has fully changed how calendar and reminder permissions are to be requested in iOS 17, to the point where permissions are automatically denied if you use the old way:

https://developer.apple.com/documentation/eventkit/accessing_the_event_store

**Comment by khuffie** [comment]
@jevonmao  - is this something on your radar? If not folks will have to stop using this library.

**Comment by jevonmao** [comment]
@khuffie Downloading Xcode beta and work in progress.

But if you are in a rush, you can checkout the new branch and implement the API calls, I already implemented rest of the code.
https://github.com/jevonmao/PermissionsSwiftUI/blob/2a05e35e967dd2a343f88dce6b0a91b76b6c9f51/Sources/PermissionsSwiftUICalendar/JMCalendarPermissionManager.swift#L67

https://github.com/jevonmao/PermissionsSwiftUI/blob/2a05e35e967dd2a343f88dce6b0a91b76b6c9f51/Sources/PermissionsSwiftUIReminder/JMRemindersPermissionManager.swift#L55

**Comment by khuffie** [comment]
@jevonmao  thanks for the quick response! No rush - if it's implemented in the next 2-3 weeks should have plenty of time before iOS 17 is released in public
