### ISSUE TITLE
[ Reject] - Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage

### ISSUE THREAD

**Issue by SNQ-2001** [jevonmao/PermissionsSwiftUI#136]
Review was rejected for the following reasons
> We noticed your app includes App Tracking Transparency permissions requests, but it encourages or directs users to accept tracking. Specifically, your app directs the user to accept tracking in the following way(s): 
>
> - A message appears before the permission request, and the user can close the message and delay the permission request with the dismissal button. The user should always proceed to the permission request after the message. 
>
> Permission requests give users control of their personal information. It is important to respect their decision about how their data is used.
>
> Next Steps
>
> To resolve this issue, please revise the permission request process in your app to not include an exit button on the message before the tracking request.
>
> If necessary, you may provide more information about why you are requesting permission to track before the request appears. > If the user is trying to use a feature in your app that won't function without tracking, you may include a notification to inform the user and provide a link to the Settings app. 

![Screenshot-0713-123644](https://github.com/jevonmao/PermissionsSwiftUI/assets/84154073/e224194a-97a5-4ad9-9d74-78a18abaa8fd)

**Comment by jevonmao** [comment]
@SNQ-2001 Assuming you are using latest version of library, I believe this was addressed by PR #118 which hides the exit button. Make sure `restrictDismissal` and `autoDismiss` are false.
