### ISSUE TITLE
[BUG] - ITMS-90683: Missing purpose string in Info.plist

### ISSUE THREAD

**Issue by connyhald** [jevonmao/PermissionsSwiftUI#140]
**Describe the bug**
Our app only uses `PermissionsSwiftUIBluetooth` and `PermissionsSwiftUINotification` still we are getting the following message from Apple.

> ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “CPS-DEV.app” bundle should contain a NSCalendarsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources.

**Smartphone (please complete the following information):**
 - Version 1.5.8

**Comment by jevonmao** [comment]
@connyhald Can I just confirm that you did not check CorePermissionsSwiftUI and PermissionsSwiftUI during package install so its not included in your binary?

**Comment by connyhald** [comment]
@jevonmao I can confirm that I have not checked `CorePermissionsSwiftUI` or `PermissionsSwiftUI`.

I have downgraded from `1.5.8` to `1.5.6` and now I don't get that messages from Apple anymore.

**Comment by Patresko** [comment]
Yes its always rejected by Apple with 1.5.8 version.
