### ISSUE TITLE
[BUG] - Photo library authorization doesnt work for limited access

### ISSUE THREAD

**Issue by ibraiz11** [jevonmao/PermissionsSwiftUI#144]
Photo library authorization returns `.authorized` for limited access, It should return `.limited`.

**To Reproduce**
1. Start the app first time and give limited access for photos.
2. Select images and it will get you to your app
3. if you use a logger or breakpoint then you will get `.authorized` not `.limited` as return value to `JMPhotoPermissionManager.photo.authorizationStatus`.

**Expected behavior**
I expect `.limited` access view to inflate not the `.authorized` gallery view. 
`JMPhotoPermissionManager.photo.authorizationStatus` should be returning `.limited`

**Desktop (please complete the following information):**
 - OS: iOS

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.7
 - Version 16.7
 
**Additional context**
Can be fixed in JPPhotoPermissionManager's authorizationStatus function to make it return accurate permission access.

**Comment by ibraiz11** [comment]
The new API is available for iOS 14+ so that needs to be bumped up to 14 from 13. It's a simple fix so if you assign it to me I can make a PR.

**Comment by jevonmao** [comment]
@ibraiz11 Yes, feel free to open a PR but I would prefer an #if available so we don't lose compatibility on iOS 13.

**Comment by ibraiz11** [comment]
This will create an access level issue as PHAccess is only available from 14+.
The @availabe annotation for 13 is not required for this class as changes are post 14 and the deprecated methods support back upto iOS 8.
