### ISSUE TITLE
[BUG] - Library conflict problem

### ISSUE THREAD

**Issue by KinmoCode** [jevonmao/PermissionsSwiftUI#156]
**Describe the bug**

**To Reproduce**
<img width="1146" alt="截屏2024-04-09 21 27 10" src="https://github.com/jevonmao/PermissionsSwiftUI/assets/14145672/6393249e-e92f-4a7e-bcba-ab7b2f1d2c5f">

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by meyusufdemirci** [comment]
@KinmoCode how did you fix it?
