### ISSUE TITLE
Allow some kind of data model to customize behaviors

### ISSUE THREAD

**Issue by jevonmao** [jevonmao/PermissionsSwiftUI#20]
Suggestion from Redditor

**Comment by a-moss** [comment]
@jevonmao Could you elaborate a bit on the feature request here? What kind of behaviors should be customized?

**Comment by jevonmao** [comment]
@a-moss Sure. I'm on my mobile device right now. I will provide a lot more detail for this issue, once I get access to my computer.

**Comment by jevonmao** [comment]
@a-moss Please reference #25, an Action issue tracking this feature. I have put all the to do items for this feature there. Since you are interested in this project, I very much appreciate your contribution.

**Comment by jevonmao** [comment]
Finished
