### ISSUE TITLE
Maybe you can add SPPermissions as link?

### ISSUE THREAD

**Issue by varabeis** [jevonmao/PermissionsSwiftUI#21]

**Comment by jevonmao** [comment]
Yeah! The original creator of SPPermissions! I have your library mentioned first sentence in README.md, I will add a link.  Actually, I should probably write an entire acknowledgment section for you. Anyways, what do you think of my SwiftUI package? It's still very work in progress, but does it resemble SPPermissions?

**Comment by varabeis** [comment]
It's have many same features and UI. If you want, I can propose some interesting things.

**Comment by jevonmao** [comment]
Already added your link, if there is nothing else I will close the issue.
