### ISSUE TITLE
Use generics to replace AnyView

### ISSUE THREAD

**Issue by johnnythedoggie** [jevonmao/PermissionsSwiftUI#22]
Using AnyView is bad practice, and if it can be replaced (and I believe it can in this case) it should be.  With just a few changes, MainView.swift would be modified to look like this:

```
struct MainView<BodyView: View>: View {
    private var showModal: Binding<Bool>
    private var bodyView: BodyView
    init(for bodyView: BodyView, show showModal: Binding<Bool>) {
        self.bodyView = bodyView
        self.showModal = showModal
    }

    var body: some View {
        bodyView
            .sheet(isPresented: showModal, content: {
                ModalView(showModal: showModal)
            })
            
    }
}
```

AnyView is used in many places and most (if not all) of them can be replaced with generics.  This won't break anyone's existing code either, the type will not be MainView, it will be MainView\<AnyView\>.  AnyView should be switched for generics in JMPermission (for the imageIcon) as well.  This helps SwiftUI update views more efficiently and prevents always casting the image to AnyView like is currently in the README:
```
.setPermissionComponent(for: .camera, 
                        image: AnyView(Image(systemName: "camera.fill")), 
                        title: "Camcorder",
                        description: "App needs to record videos")
```

**Comment by jevonmao** [comment]
@johnnythedoggie Thank you for bringing this up! I absolutely agree with you. Would you like to tackle this and open a pull request? If not, I will take care of this.

**Comment by jevonmao** [comment]
@johnnythedoggie I would appreciate it if you can work on this and open a PR. It looks nice to have more than 1 contributor. New [version](https://github.com/jevonmao/PermissionsSwiftUI/releases/tag/1.1.0) is out, my goal is to implement this by v1.1.1

**Comment by johnnythedoggie** [comment]
@jevonmao I'm still learning GitHub, so it may take me a bit.  I do plan to open a PR and make the change, but I'm confused how to do that.  I'll figure it out soon (hopefully) and go for it.  I'll ask if I have questions.

**Comment by jevonmao** [comment]
@johnnythedoggie No problem at all. If you are not sure, read [this](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/) article that guides you through the entire process. 
For step 3, simply name the branch `#22-any-view` to reference this issue number.
 Make sure you also have Xcode installed.

**Comment by jevonmao** [comment]
@johnnythedoggie Are you still interested in working on this issue? Just give me a status update please. If not, I will go ahead and do it.

**Comment by jevonmao** [comment]
I tried to do this, but for variety reasons, the `JMPermission` structure simply will not allow the pass in of another type other than `Image` if a generic is used to replace AnyView. **`AnyView` is a completelu type erased view, while a generic only works with 1 type that cannot be changed at runtime.** Will close for now due to inactivity.
