### ISSUE TITLE
Add ability to customize accent colour

### ISSUE THREAD

**Issue by khuffie** [jevonmao/PermissionsSwiftUI#35]
The default colour is blue for PermissionsSwiftUI, which doesn't quite work with my app's design.

For the permission images, I can pass in custom images and provide them with my preferred accent colour.

For the buttons, there seems to be no way to customize them. I see in the source code "ButtonStatusColor", but as it's not a public class I cannot extend it and over-ride it.

Being able to pass in an accent colour that when calling .JMModal would be great!

**Comment by jevonmao** [comment]
@khuffie Great suggestion. This feature will be added ASAP!

**Comment by khuffie** [comment]
@jevonmao that's great! Let me know, anxious to release it :) 

(PS: it would be good if the accent colour also affects the images :)

**Comment by jevonmao** [comment]
@khuffie It's done! Worked on the project for the entire afternoon, and in the latest 1.2.2 release, you should be able to customize all the buttons, all the colors, for all states. 
Use the `setAllowButtonColor(to colors:AllButtonColors)` view modifier

**Comment by jevonmao** [comment]
@khuffie Actually, looking at this new API, it's badly designed. I don't like it, too complicated and unnecessary. I will rework this feature, and use a single modifier to change accent color of buttons and the image icons.

**Comment by khuffie** [comment]
@jevonmao  no worries! Take your time :)

**Comment by jevonmao** [comment]
@khuffie The feature is ready!. Please update to v1.2.3, and reference README.md if needed.
