### ISSUE TITLE
prevent dismiss modal before allowing all permissions

### ISSUE THREAD

**Issue by gharary** [jevonmao/PermissionsSwiftUI#40]
**Describe the solution you'd like**

I need to prevent user from dismissing modal view before allowing all permissions.

**Comment by jevonmao** [comment]
@gharary Thank you for this suggestion, I think it's great! BTW, what do you think about adding a error haptic when user tries to dismiss the view without allowing all permissions? Also, what do you think should happen if user explicitly deny some permissions?

**Comment by gharary** [comment]
@jevonmao adding error haptic is so great. It improves the UI/UX so great.
About denying some permissions, we can pass the permission windows if the user has decided about all permissions needed (Allow or Deny). If denied, the user can be prompted again during the app to allow that permission.

**Comment by jevonmao** [comment]
@gharary Sounds good! Stay tuned, this feature should be done within this week. 🙌

**Comment by jevonmao** [comment]
@gharary Done. Please make sure your package is on the newest version, reference [here](https://github.com/jevonmao/PermissionsSwiftUI#restrict-dismissal) if needed.

**Comment by jevonmao** [comment]
The haptic error still needs work (because SwiftUI does not offer a native way to react to a dismiss gesture), and it will take a while before I figure out the UIKit stuff underneath.

**Comment by gharary** [comment]
So wonderful to see those changes soo quick. 👏
