### ISSUE TITLE
[BUG] - For Health permissions, read and write permissions are switched.

### ISSUE THREAD

**Issue by khuffie** [jevonmao/PermissionsSwiftUI#41]
I was getting the following error when trying to authorize HealthKit permissions:

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Authorization to share the following types is disallowed: HKQuantityTypeIdentifierAppleExerciseTime, HKQuantityTypeIdentifierAppleStandTime'
`
I was pretty sure that I was initializing HKAccess with the correct permissions for read and write (aka toShare). 

Digging into the code, In HMHealthPermissionManager.requestPermission, line 93 and 94 are as follows:

```
        healthStore.requestAuthorization(toShare: Set(healthPermission?.readPermissions ?? []),
                                         read: Set(healthPermission?.writePermissions ?? [])) { authorized, error in
```

"toShare" should be looking at the .writePermissions, not the readPermissions, so it should be:

```
        healthStore.requestAuthorization(toShare: Set(healthPermission?.writePermissions ?? []),
                                         read: Set(healthPermission?.readPermissions ?? [])) { authorized, error in
```

Btw: it would be good to add documentation on how to request health permissions in the README, I had to dig into the source code to figure it out :)

**Comment by jevonmao** [comment]
Nice catch! I will fix the bug ASAP. About adding documentation on how to request health permissions, I thought you guys can figure it out with `Option + Left Click` quick help documentation on relevant structs and enums, and a lot of the instructions are in there. But still, I will add some instructions in README.md.

**Comment by jevonmao** [comment]
#khuffie Try the newest version please.
