### ISSUE TITLE
can you add cocoapods?

### ISSUE THREAD

**Issue by wangrui460** [jevonmao/PermissionsSwiftUI#61]
can you add cocoapods?

**Comment by jevonmao** [comment]
@wangrui460 Thank you very much for the suggestion!  Previously I tried and I had trouble figuring it out, but yes, I can try. 

In the meantime, you can use all of PermissionSwiftUI through Swift Package Manager!

**Comment by jevonmao** [comment]
@wangrui460 You can install PermissionsSwiftUI by Cocoapods: `pod 'PermissionsSwiftUI'`🙌. If there is any issue, feel free to follow up.
