### ISSUE TITLE
[BUG] - Using .JMModal with .sheet cause modal not to show

### ISSUE THREAD

**Issue by gharary** [jevonmao/PermissionsSwiftUI#62]
**Describe the bug**

I'm using .JMModal on my login view and also in this view I have .sheet but .JMModal won't show when I have .sheet.
If I delete that lines of code, then .JMModal show perfectly.

<img width="467" alt="Screen Shot 2021-03-31 at 11 09 24 PM" src="https://user-images.githubusercontent.com/16289125/113194246-29cc8e80-9276-11eb-8eb3-b7a490f899af.png">

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 11.2.3
 - Browser [e.g. chrome, safari] Safari

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 8, Simulator (iPhone 12 Pro)
 - OS: [e.g. iOS8.1] iOS 14.5
 - Browser [e.g. stock browser, safari] safari

**Additional context**

**Comment by jevonmao** [comment]
@gharary I tried it on my side, and I was able to successfully reproduce. 
I think you can solve this problem by combining the 2 modals into 1, and conditionally show `JMModal` on `EmptyView()` or your custom view, `GetNumberRoot()` . For example:

```Swift
.sheet(isPresented: showPermission.combine(with: showMobileLogin), content: {
            if showPermission {
                EmptyView()
                    .JMModal(showModal: .constant(true), for: [.camera,.location,.contacts])
            }
            else if showMobileLogin {
                
            }

})
//Extension Binding wrapper for Binding booleans
extension Binding where Value == Bool{
    func combine(with value2: Binding<Bool>) -> Binding<Bool>{
        //Combine two Binding Bool conditions with OR operator
        return self.wrappedValue || value2.wrappedValue ? .constant(true) : .constant(false)
    }
}
```

**Comment by jevonmao** [comment]
I hope that worked. By the way, I removed the bug label because this behavior is not a bug, using 2 `.sheet` modifiers will also produce this behavior because SwiftUI don't know what to do.

**Comment by gharary** [comment]
Thanks for your great idea. Problem Solved!

**Comment by gharary** [comment]
Thanks for your great idea. Problem Solved!
