### ISSUE TITLE
Update to platform iOS 14

### ISSUE THREAD

**Issue by rahulbhalley** [jevonmao/PermissionsSwiftUI#67]
**Is your feature request related to a problem? Please describe.**
I am building an app for iOS 14 but this package is only available for iOS 13.

**Describe the solution you'd like**
Update this package for use with iOS 14 in `Package.swift`.

**Describe alternatives you've considered**
No alternatives yet. 

**Additional context**
N/A.

**Comment by jevonmao** [comment]
@rahulbhalley oh my god, for this whole time? I will update ASAP, thank you for letting me know.

**Comment by rahulbhalley** [comment]
Oops 😬, I'm sorry. It does work with iOS 14. I just had to restart my Xcode.
