### ISSUE TITLE
Unsafe Flags - Can't build any longer

### ISSUE THREAD

**Issue by macteuts** [jevonmao/PermissionsSwiftUI#71]
**Describe the bug**
Here is the alert I get when trying to build:
The package product 'PermissionsSwiftUI' cannot be used as a dependency of this target because it uses unsafe build flags.
This happens when updating to versions 1.4.0 or 1.4.1. 
Version 1.3.0 still builds.

**To Reproduce**
Just build & run

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [iOS 14]

**Additional context**

**Comment by jevonmao** [comment]
@macteuts Got you, I made a mistake, this is supposed to be fixed in 1.4.1. I will fix this.

**Comment by jevonmao** [comment]
1.4.0 should build, because the bug is accidentally introduced in 1.4.1. Can you verify that? If so, you can manually choose 1.4.0 in Xcode until I fix this bug.

**Comment by jevonmao** [comment]
@macteuts I already pushed an update to fix v1.4.1. If there is nothing else, I will close the issue.

**Comment by macteuts** [comment]
Sorry for the late answer. I'll test it today. thanks for the swift answer ^^. I'll let you know asap

**Comment by macteuts** [comment]
It's working fine! bravo & thanks.
