### ISSUE TITLE
[BUG] -  Health authorization read only crash

### ISSUE THREAD

**Issue by gharary** [jevonmao/PermissionsSwiftUI#72]
**Describe the bug**

PermissionSwiftUI 1.4.1
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Must request authorization for at least one data type'`

**To Reproduce**
```
let readData = Set([HKObjectType.workoutType(),
                                    HKObjectType.quantityType(forIdentifier: .stepCount)!,
                                    HKObjectType.quantityType(forIdentifier: .distanceWalkingRunning)!,
                                    HKObjectType.quantityType(forIdentifier: .activeEnergyBurned)!
                                    ,HKObjectType.quantityType(forIdentifier: .appleStandTime)!
                                    ])

```
`.JMModal(showModal:$showPermission,for:[.locationAlways,.health(categories: .init(read: readData)),.notification])
`

**Expected behavior**

in `mapPermissionAuthorizationStatus`, `input`  is `Set<HKSampleType>`, however I'm using `HKObjectType` and it cause error

***Update:
Tried with `HKSampleType` but still crash as I click to allow permission of Health.

*** update:
tried to downcast to PermissionSwiftUI 1.3.0, everything working fine!

**Comment by jevonmao** [comment]
@gharary Acknowledged. Will try to reproduce and confirm this bug later today.

**Comment by jevonmao** [comment]
Please try newest version @gharary
