### ISSUE TITLE
[BUG] - Trying to ask for tracking permissions with iOS < 14.5 will cause crash

### ISSUE THREAD

**Issue by smaldd14** [jevonmao/PermissionsSwiftUI#75]
**Describe the bug**
If you are not using iOS v14.5, the handlePermissionRequest() 
permission.getPermissionManager()?.init(permissionType: permission) will return nil because version is less than 14.5...
This should be correct behavior, however, the next line in handlePermissionRequest() tries to force unwrap permissionManager by doing permissionManager!.requestPermission...

Would a if permissionManager != nil  {} check be enough to suffice?

**To Reproduce**
1. use iOS simulator with v14.4, add .tracking to JMModal, watch crash

**Expected behavior**
Should not crash with iOS versions < 14.5... Should just not show tracking permission option

**Comment by jevonmao** [comment]
@smaldd14 Please try newest 1.4.3 and see if it works.

**Comment by smaldd14** [comment]
@jevonmao The button successfully changes to 'Allowed' but the modal that is showing still does not dismiss.

**Comment by smaldd14** [comment]
@jevonmao It no longer crashes, but in PermissionType.swift, I see that you say  @available(iOS 14, *) case tracking... Correct me if I'm wrong, but I thought tracking was only available with iOS 14.5 and  newer. That is what this link says below. https://developer.apple.com/app-store/user-privacy-and-data-use/

It seems to work fine, however, like the comment in the other issue I have created, the JMModal does not automatically dissappear, and setting autoDismissal : true, messes things up

**Comment by jevonmao** [comment]
@smaldd14 If you look into the v1.4 migration guide, it says: 

`JMModal` will not be dismissed by swiping. The `autoDismiss` still work, but the user will always have to use the close button if `autoDismiss` is enabled. JMAlert is not affected.

HOWEVER, I plan to continue debugging and fixing this behavior bug because it's not optimal.

I will reproduce what you mentioned that setting `autoDismiss` to true mess things up, and we go from there.

**Comment by jevonmao** [comment]
@smaldd14 Yes you are correct, tracking permission only works above 14.5. But I made it available for iOS 14.0 since there is no compiler warning or error for that, meaning Apple's API is marked for 14.0.

**Comment by jevonmao** [comment]
Resolved.
