### ISSUE TITLE
[BUG] - When submitting app to app store connect, I must include ALL Privacy description strings. Even for permissions I am not using

### ISSUE THREAD

**Issue by smaldd14** [jevonmao/PermissionsSwiftUI#77]
**Describe the bug**
I only use Location, notification permissions from this swift package. Yet I am asked to include all of these different type of usage description strings. I believe this is because this swift package uses all of the permission types in PermissionsManager. Is there a way for me to not include all usage descriptions?

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSContactsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more

**Comment by jevonmao** [comment]
@smaldd14 Well that's bad. I think one potential solution is to break PermissionsSwiftUI into 13 different sub-packages that you add separately for each type of permission. I will try to come up with a fix.

**Comment by jevonmao** [comment]
The sub-package idea is probably just as bad. What do you think if I provide a copypasta boilerplate that includes every single permission's info.plist in the README.md? I will also look into ways to automatically generate info.plist string perhaps?

**Comment by smaldd14** [comment]
@jevonmao that would be great! Thanks for being so helpful.

**Comment by jevonmao** [comment]
@smaldd14 PermissionsSwiftUI v1.5.0 is available now! Remove PermissionsSwiftUI in SPM and reinstall and only add permissions needed in the checkboxes. Let me know if it works.

**Comment by jevonmao** [comment]
Implemented in v1.5.0.
