### ISSUE TITLE
Need to add FaceID permission

### ISSUE THREAD

**Issue by jevonmao** [jevonmao/PermissionsSwiftUI#80]
This is a placeholder, I will elaborate further

**Comment by N3v1** [comment]
Hi @jevonmao,
Is someone working on this task if no maybe I can look into it. Can you provide me a description or guide how to implement new permissions?

Thank you in advance
Best regards
NH

**Comment by jevonmao** [comment]
@N3v1 Hi, I believe https://github.com/jevonmao/PermissionsSwiftUI/blob/main/docs/New_Permission_Guide.md should be of some help.

**Comment by N3v1** [comment]
Thx for the guide - I'll look into it and create a PR as soon as possible 👍

**Comment by N3v1** [comment]
@jevonmao, I have created a pull request that fixes the issues with biometric authentication methods. The PR number is #148.

Best regards
NH
