### ISSUE TITLE
JMModal and JMAlert not recognized 

### ISSUE THREAD

**Issue by Itlink75** [jevonmao/PermissionsSwiftUI#89]
Was working fine for months are suddenly likely due to update, wouldn t compile anymore.

view has no type JMAlert nore JMModal
I tried to uninstall and reinstall but no difference . CLean buil , nodifference. Very similar to a closed issue:
who had those elements
XCode version 12.4
MacOS Catalina 10.15.7
simulator model iPhone 12 pro (although doesn't even open up simulator because it fails before this
deployment version iOS 14.4

i have XCode version 12.4
MacOS Catalina 10.15.7
simulator model iPhone 11 pro
deployment version iOS 14.4
 I would like to downgrade but i don t know how to retrieve myprevious version from github Any help to retrieve 1,4 would be welcome

**Comment by jevonmao** [comment]
@Itlink75 Hi there! Thanks for the issue report.
## Recommended Fix
If your view has no type `JMAlert` nor `JMModal`, it's likely that Xcode did not fetch, link, import or compile the PermissionsSwiftUI package properly. 

After v1.5.0, you might want to reinstall PermissionsSwiftUI and select only the submodules for permissions you use.

Please make sure that these setups are proper
1. Click on the blue project configuration file in the file inspector
2. Click on the iOS target (if you have multiple)
3. Verify that in the `Frameworks, libraries, and embedded content` section, you have the proper libraries imported.
You either need 1 submodule called PermissionsSwiftUI, OR (recommended) 1 or more submodules for permissions types you need to use.
You should NOT have the CorePermissionsSwiftUI module imported.
![image](https://user-images.githubusercontent.com/64660730/122663050-8e4c0b00-d14c-11eb-9293-1cbcc91ea23a.png)
4. Verify that in the code file where `JMModal` or `JMAlert` is referenced, you are importing multiple permission submodules in the file header. 
```swift
///Example.swift
import PermissionsSwiftUINotifications
import PermissionsSwiftUILocation
import PermissionsSwiftUITracking

...

var body: some View {
      .JMModal()
}
```

## Downgrade to v1.4.0
If you want to downgrade to a previous version that works, you may do so. In Xcode, click on `Add Package Dependency`, click next, and it will prompt you to choose package options.
![image](https://user-images.githubusercontent.com/64660730/122663081-d23f1000-d14c-11eb-976c-70aa693e568f.png)
Here, you will select `exact version` and put in your desired version of PermissionsSwiftUI (eg. 1.4.0).

**Comment by Itlink75** [comment]
Hello, 
with auto update , it wouldn t work . By reimporting main module 1.5 it would not work also .
Reimporting each module and not the main one makes the app compile again . Thanx for the support !
