### ISSUE TITLE
[BUG] - Healthkit access shows denied even after allow - v 1.5.1

### ISSUE THREAD

**Issue by gharary** [jevonmao/PermissionsSwiftUI#90]
I'm using version 1.5.1, and using Healthkit with PermissionUIHealth framework just to read some data, but when I click allow, JMModal shows `denied` not `allowed`.

**Comment by jevonmao** [comment]
@gharary I don't recall this issue when testing, but I'm I aking a look.

**Comment by jevonmao** [comment]
@gharary Okay got it, I confirmed this is a bug. The request is not affected though, only the UI is bug.

**Comment by jevonmao** [comment]
v1.5.2 released. Should fix this issue.
