### ISSUE TITLE
[BUG] - autoDismiss, dismiss the permissionView even by clicking on our of multiple items

### ISSUE THREAD

**Issue by gharary** [jevonmao/PermissionsSwiftUI#93]
**Describe the bug**

I have a JMModal with 3 permissions [Health, Motion, Notification].

By clicking any of them, with `autoDismiss` set to `true`, the view disappears without waiting for other permissions to be set.

Here is my code:

```
.JMModal(showModal: $showPermission, for: [.health(categories: .init(read:readData)),.notification,.motion],
autoDismiss: true,
autoCheckAuthorization: true,
restrictDismissal: true)
```

**Expected behavior**
disabling `autoDismiss` keeps the view open until manually dismiss it.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 14.5
 - Version [e.g. 22] 1.5.2

**Comment by jevonmao** [comment]
Ok let me investigate this.

**Comment by jevonmao** [comment]
Need a few more days, on trip right now.

**Comment by jevonmao** [comment]
@gharary Try v1.5.3 and let me know if it's fixed.

**Comment by gharary** [comment]
Problem solved. Thanks
