### ISSUE TITLE
.JMAlert(showModal: x, for: [y], restrictDismissal: z) not an option

### ISSUE THREAD

**Issue by smaldd14** [jevonmao/PermissionsSwiftUI#96]
### Overview
There is no JMAlert with option to restrictDismissal. There IS one for JMModal, but I want to use JMAlert.

### Action items
 Option for .JMAlert(showModal: self.$showModal, for: [.notification, .tracking], restrictDismissal: false)

**Comment by jevonmao** [comment]
@smaldd14 Really??! This is interesting, it should be exactly same for both, I will get this fixed.

**Comment by xoniq** [comment]
Also noticed this after switching from modal to alert.

**Comment by jevonmao** [comment]
@xoniq @smaldd14 Please try v1.5.4
