### ISSUE TITLE
[BUG] - JMNotificationPermissionManager does not work with iOS 15

### ISSUE THREAD

**Issue by cipolleschi** [jevonmao/PermissionsSwiftUI#97]
**Describe the bug**
I was building my project with iOS 15 and the library won't build.
Starting from iOS 15, [`UIApplication.shared.registerForRemoteNotifications()`](https://github.com/jevonmao/PermissionsSwiftUI/blob/main/Sources/PermissionsSwiftUINotification/JMNotificationPermissionManager.swift#L65) cannot be used in extensions anymore and the error suggests to use a `ViewController` implementation instead.

**To Reproduce**
1. Install Xcode 13
2. Build the project
3. Observe the build process fail

**Expected behavior**
The framework should build

**Smartphone (please complete the following information):**
 - OS: iOS 15

**Comment by jevonmao** [comment]
@cipolleschi I will get this fixed ASAP.

**Comment by jevonmao** [comment]
Follow up, I have attempted to reproduce this bug on Xcode 13, standard SwiftUI project for iOS, targeting iOS 15 and building for iOS 15 simulator. And I am not able to reproduce the error you are talking about. @cipolleschi

**Comment by cipolleschi** [comment]
Thanks for being that prompt. We are seeing the error in a project with a WatchOS app associated.
I'll try to create a sample project and to attach it here as reference!

**Comment by cipolleschi** [comment]
Hey, this is the example project with the error. Is an Empty WatchOS + iOS project in which I just added the PermissionSwiftUI Swift Package.

Let me know if I can help in any way!
[TestPermissionPackage.zip](https://github.com/jevonmao/PermissionsSwiftUI/files/7105912/TestPermissionPackage.zip)

**Comment by jevonmao** [comment]
A little bit busy for the past week, I will try to get to this today.

**Comment by jevonmao** [comment]
Will verify all WatchOS(also possibly other less attended to platforms like tvOS) PermissionsSwiftUI APIs, against newest iOS 17
